### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by desgua** [arthur-jacquin/edit#1]
After reading your email to suckless list, I wanted to try your text editor. But I couldn't figure out how to fix this compile error: 
$ make
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -DVERSION="0.3.2"
LDFLAGS  = -static
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -DVERSION=\"0.3.2\" edit.c
In file included from edit.c:10:
termbox2.h: In function ‘tb_present’:
termbox2.h:1621:25: warning: implicit declaration of function ‘wcwidth’ [-Wimplicit-function-declaration]
 1621 |                     w = wcwidth((wchar_t)back->ch);
      |                         ^~~~~~~
termbox2.h: In function ‘tb_strerror’:
termbox2.h:1989:13: warning: implicit declaration of function ‘strerror_r’; did you mean ‘strerror’? [-Wimplicit-function-declaration]
 1989 |             strerror_r(global.last_errno, global.errbuf, sizeof(global.errbuf));
      |             ^~~~~~~~~~
      |             strerror
termbox2.h: In function ‘init_term_attrs’:
termbox2.h:2056:5: warning: implicit declaration of function ‘cfmakeraw’ [-Wimplicit-function-declaration]
 2056 |     cfmakeraw(&tios);
      |     ^~~~~~~~~
termbox2.h: In function ‘init_resize_handler’:
termbox2.h:2209:22: error: storage size of ‘sa’ isn’t known
 2209 |     struct sigaction sa;
      |                      ^~
termbox2.h:2212:9: warning: implicit declaration of function ‘sigaction’ [-Wimplicit-function-declaration]
 2212 |     if (sigaction(SIGWINCH, &sa, NULL) != 0) {
      |         ^~~~~~~~~
termbox2.h:2209:22: warning: unused variable ‘sa’ [-Wunused-variable]
 2209 |     struct sigaction sa;
      |                      ^~
termbox2.h: In function ‘tb_deinit’:
termbox2.h:2345:46: error: ‘struct sigaction’ has no member named ‘sa_handler’
 2345 |     sigaction(SIGWINCH, &(struct sigaction){.sa_handler = SIG_DFL}, NULL);
      |                                              ^~~~~~~~~~
termbox2.h:2345:59: warning: excess elements in struct initializer
 2345 |     sigaction(SIGWINCH, &(struct sigaction){.sa_handler = SIG_DFL}, NULL);
      |                                                           ^~~~~~~
termbox2.h:2345:59: note: (near initialization for ‘(anonymous)’)
termbox2.h:2345:44: error: invalid use of undefined type ‘struct sigaction’
 2345 |     sigaction(SIGWINCH, &(struct sigaction){.sa_handler = SIG_DFL}, NULL);
      |                                            ^
termbox2.h: In function ‘read_terminfo_path’:
termbox2.h:2446:15: warning: implicit declaration of function ‘fileno’ [-Wimplicit-function-declaration]
 2446 |     if (fstat(fileno(fp), &st) != 0) {
      |               ^~~~~~
make: *** [Makefile:18: edit.o] Error 1

**Comment by arthur-jacquin** [comment]
> Le 27 sept. 2023 à 14:39, desgua ***@***.***> a écrit :
> 
> ﻿
> After reading your email to suckless list, I wanted to try your text editor. But I couldn't figure out how to fix this compile error:
> $ make
> CFLAGS = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -DVERSION="0.3.2"
> LDFLAGS = -static
> CC = cc
> cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -DVERSION="0.3.2" edit.c
> In file included from edit.c:10:
> termbox2.h: In function ‘tb_present’:
> termbox2.h:1621:25: warning: implicit declaration of function ‘wcwidth’ [-Wimplicit-function-declaration]
> 1621 | w = wcwidth((wchar_t)back->ch);
> | ^~~~~~~
> termbox2.h: In function ‘tb_strerror’:
> termbox2.h:1989:13: warning: implicit declaration of function ‘strerror_r’; did you mean ‘strerror’? [-Wimplicit-function-declaration]
> 1989 | strerror_r(global.last_errno, global.errbuf, sizeof(global.errbuf));
> | ^~~~~~~~~~
> | strerror
> termbox2.h: In function ‘init_term_attrs’:
> termbox2.h:2056:5: warning: implicit declaration of function ‘cfmakeraw’ [-Wimplicit-function-declaration]
> 2056 | cfmakeraw(&tios);
> | ^~~~~~~~~
> termbox2.h: In function ‘init_resize_handler’:
> termbox2.h:2209:22: error: storage size of ‘sa’ isn’t known
> 2209 | struct sigaction sa;
> | ^~
> termbox2.h:2212:9: warning: implicit declaration of function ‘sigaction’ [-Wimplicit-function-declaration]
> 2212 | if (sigaction(SIGWINCH, &sa, NULL) != 0) {
> | ^~~~~~~~~
> termbox2.h:2209:22: warning: unused variable ‘sa’ [-Wunused-variable]
> 2209 | struct sigaction sa;
> | ^~
> termbox2.h: In function ‘tb_deinit’:
> termbox2.h:2345:46: error: ‘struct sigaction’ has no member named ‘sa_handler’
> 2345 | sigaction(SIGWINCH, &(struct sigaction){.sa_handler = SIG_DFL}, NULL);
> | ^~~~~~~~~~
> termbox2.h:2345:59: warning: excess elements in struct initializer
> 2345 | sigaction(SIGWINCH, &(struct sigaction){.sa_handler = SIG_DFL}, NULL);
> | ^~~~~~~
> termbox2.h:2345:59: note: (near initialization for ‘(anonymous)’)
> termbox2.h:2345:44: error: invalid use of undefined type ‘struct sigaction’
> 2345 | sigaction(SIGWINCH, &(struct sigaction){.sa_handler = SIG_DFL}, NULL);
> | ^
> termbox2.h: In function ‘read_terminfo_path’:
> termbox2.h:2446:15: warning: implicit declaration of function ‘fileno’ [-Wimplicit-function-declaration]
> 2446 | if (fstat(fileno(fp), &st) != 0) {
> | ^~~~~~
> make: *** [Makefile:18: edit.o] Error 1
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 
Hello,

On the compilers I tried the non-C99 functions in termbox2.h only generated warnings, not errors. Which compiler do you use ?

You should be fine by deleting the -std=c99 flag in CFLAGS (in config.mk). Sorry for the annoyance and thanks for the feedback, I will delete the -std=c99 flag from the default configuration or fix termbox2.h to C99 compliance.

If deleting the flag does not work, please let me know. Otherwise, happy editing ;)

Arthur

**Comment by desgua** [comment]
Thank you so much!
